stages:
  prepare:
    cmd: python src/split_train_test.py --data_dir /Users/sylvainpicard/Code/PRO/EUCLID/DVC/sat-mlflow/data/original/
      --out_dir /Users/sylvainpicard/Code/PRO/EUCLID/DVC/sat-mlflow/data/ --train_size
      0.7
    deps:
    - data/original
    - src/split_train_test.py
    params:
    - prepare.data_dir
    - prepare.out_dir
    - prepare.train_size
    outs:
    - data/test
    - data/train

  train:
    cmd: python src/train.py
    deps:
    - data/train
    - src/train.py
    params:
    - train.batch_size
    - train.epochs
    - train.log_interval
    - train.train_dir
