prepare:
  data_dir: "/Users/sylvainpicard/Code/PRO/EUCLID/DVC/sat-mlflow/data/original"
  out_dir: "/Users/sylvainpicard/Code/PRO/EUCLID/DVC/sat-mlflow/data/"
  train_size: 0.7
train:
  train_dir: "/Users/sylvainpicard/Code/PRO/EUCLID/DVC/sat-mlflow/data/train"
  batch_size: 50
  epochs: 1
  log_interval: 10